# Generated by Django 5.1.7 on 2026-03-15 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.URLField(max_length=500)),
                ('credentials', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('failed', 'Failed')], default='idle', max_length=10)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'booking_system',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('external_id', models.CharField(max_length=255)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('booking_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='booking_systems.bookingsystem')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('external_id', models.CharField(max_length=255)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('booking_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='booking_systems.bookingsystem')),
            ],
            options={
                'db_table': 'provider',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('external_id', models.CharField(max_length=255)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('booking_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='booking_systems.bookingsystem')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='booked', max_length=10)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('external_id', models.CharField(max_length=255)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('booking_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='booking_systems.bookingsystem')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='booking_systems.customer')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='booking_systems.provider')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='booking_systems.service')),
            ],
            options={
                'db_table': 'appointment',
                'ordering': ['start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['booking_system', 'last_name', 'first_name'], name='customer_booking_c09c5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('booking_system', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['booking_system', 'last_name', 'first_name'], name='provider_booking_505081_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='provider',
            unique_together={('booking_system', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['booking_system', 'name'], name='service_booking_fc986b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('booking_system', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['booking_system', 'start_time'], name='appointment_booking_abc1f9_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['booking_system', 'status'], name='appointment_booking_773d17_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['start_time', 'end_time'], name='appointment_start_t_eca036_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('booking_system', 'external_id')},
        ),
    ]
