# Generated by Django 5.1.7 on 2026-03-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsystem',
            name='last_sync_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
